version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
  kanboard:
    container_name: kanboard
    image: kanboard:mib
    depends_on:
      - db
    ports:
      - "8088:80"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/kanboard
volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
  db:

